### ISSUE TITLE
W4sp API Issues

### ISSUE THREAD

**Issue by MJMODZZ-V3** [Im4wasp/W4SP-Stealer-Sourcecode#14]
So first of all in keys.py the first line there are random characters
@@ -0,0 +1,151 @@
they caused me an error so I deleted them. When I run bot.py i get this error
```
  File "C:\Users\\W4SP-Stealer-Sourcecode\W4SP-API\bot.py", line 221
    elif content in ('>line', '>script'):
    ^^^^
SyntaxError: invalid syntax
```
Ive setup it like in the video but im on windows.

**Comment by Im4wasp** [comment]
ty i updated both files

**Comment by MJMODZZ-V3** [comment]
> ty i updated both files

What do i have to put into
```py
admin = [, ]
```
Is it serverID, Channel ID or BOTID?
and in what Format?

And what to put into
```py
api = ''"
```
Is it my host?
