### ISSUE TITLE
Injector Problems

### ISSUE THREAD

**Issue by MJMODZZ-V3** [Im4wasp/W4SP-Stealer-Sourcecode#4]
Im ACD-MJMODZZ, my GitHub got closed thats why I create a new issue

its maybe because of the missing obfuscation, I used hyperion obfuscator before which did not worked for me. If I just use the script url with webhook and paste it into the Injector and start the injector i get many errors with request.py and the URL itself. I dont know how to use it

**Comment by Im4wasp** [comment]
what ?
give an example

**Comment by MJMODZZ-V3** [comment]
> what ? give an example

We fixed it, it was not working because we did used discord for Script hosting which did not worked. Another Problem we have is the payload line, do I encrypt the setup like code with b64 and just replace it with `%Payload%` or do i have to encrypt the link for the setup line?

**Comment by Im4wasp** [comment]
so

1. you take the small setup script
    - replace INJECTOR_LINK with the injector.py url (don't use discord)
    - encode this script in base64
 
2. replace %PAYLOAD% witht the base64 script you just did

then ur ready, if you run this one liner, it will install and run wasp files
u can hide this one liner anywhere in ur script

**Comment by MJMODZZ-V3** [comment]
> so
> 
> 1. you take the small setup script
>    
>    * replace INJECTOR_LINK with the injector.py url (don't use discord)
>    * encode this script in base64
> 2. replace %PAYLOAD% witht the base64 script you just did
> 
> then ur ready, if you run this one liner, it will install and run wasp files u can hide this one liner anywhere in ur script

Thats exactly what I did but the software itself did not worked anymore. Also is it possible to compile everything to an exe so I can infect Devices where python is not installed?

**Comment by MJMODZZ-V3** [comment]
> so
> 
> 1. you take the small setup script
>    
>    * replace INJECTOR_LINK with the injector.py url (don't use discord)
>    * encode this script in base64
> 2. replace %PAYLOAD% witht the base64 script you just did
> 
> then ur ready, if you run this one liner, it will install and run wasp files u can hide this one liner anywhere in ur script

So for some reason it manages to kill my chrome every time, but I cannot find any code which does that

**Comment by Im4wasp** [comment]
> Also is it possible to compile everything to an exe so I can infect Devices where python is not installed?

yeah it is, maby u need to to a few modifications

**Comment by Im4wasp** [comment]
> So for some reason it manages to kill my chrome every time, but I cannot find any code which does that

the stealer has to kill chrome to retrieve wallets extentions data

**Comment by MJMODZZ-V3** [comment]
> > So for some reason it manages to kill my chrome every time, but I cannot find any code which does that
> 
> the stealer has to kill chrome to retrieve wallets extentions data

It does not. Personally I made a RAT which can steal aio without that. Its manually just getting the safed data and it will decrypt it

**Comment by iloveyumyumshrimpnoodles** [comment]
> > > So for some reason it manages to kill my chrome every time, but I cannot find any code which does that
> > 
> > 
> > the stealer has to kill chrome to retrieve wallets extentions data
> 
> It does not. Personally I made a RAT which can steal aio without that. Its manually just getting the safed data and it will decrypt it

It needs to kill Chrome because else the tool will get an error that the file is busy. This is because the code tries to copy the SQL database to a seperate file, which is then used to retrieve all the data from. 
AFAIK (i haven't been on Windows in a long time) if you simply read from the original database file, you can retrieve the contents without needing to kill Chrome but since a lot of people just rip from eachother you'll see that a lot of projects use the same code (kill chrome, copy database and retrieve cookies, history etc etc).

Not sure tho, since like i said i haven't been on Windows in a while

**Comment by Im4wasp** [comment]
1. The passwd/cookie stealer doesn't kill the browser, plz read the code
2. The extension stealer kills the browser. Try to retrieve the content of a file that already open in an other process...
3. "Parse error: database is locked (5)" that's one of the reasons we copy the database file :)

Plz do research/read the code before answering

**Comment by iloveyumyumshrimpnoodles** [comment]
> 1. The passwd/cookie stealer doesn't kill the browser, plz read the code
> 
>     2. The extension stealer kills the browser. Try to retrieve the content of a file that already open in an other process...
> 
>     3. "Parse error: database is locked (5)" that's one of the reasons we copy the database file :)
> 
> 
> Plz do research/read the code before answering

That's what i said, no? "It needs to kill Chrome because else the tool will get an error that the file is busy", "This is because the code tries to copy the SQL database to a seperate file, which is then used to retrieve all the data from"

**Comment by iloveyumyumshrimpnoodles** [comment]
I meaned "It needs to kill Chrome because else the tool will get an error that the file is busy. Hence why the code tries to copy the SQL database to a seperate file, which is then used to retrieve all the data from."
My bad

**Comment by Im4wasp** [comment]
"if you simply read from the original database file, you can retrieve the contents without needing to kill Chrome but since a lot of people just rip from eachother you'll see that a lot of projects use the same code"

**Comment by iloveyumyumshrimpnoodles** [comment]
> "if you simply read from the original database file, you can retrieve the contents without needing to kill Chrome but since a lot of people just rip from eachother you'll see that a lot of projects use the same code"

Perhaps i was using an older version, but when i was testing on Windows i could read from the SQL database without needing to kill chrome. It seems like newer versions do require you to kill Chrome tho, because it has locked the database file preventing reads and writes

**Comment by Im4wasp** [comment]
Depends on the browser, chrome will let you read the deb
But more secure browsers like Opera won't let you. Also, most recent AV can detect if you try to open those files directly, so copying it is a good solution

**Comment by iloveyumyumshrimpnoodles** [comment]
> Depends on the browser, chrome will let you read the db But more secure browsers like Opera won't let you. Also, most recent AV can detect if you try to open those files directly, so copying it is a good solution

AV's can detect a lot more than just file reading and writing. They hook a lot of malicious functions (like LoadLibraryA, SetWindowsHookEx, CreateRemoteThread and more).

In python you can try using direct syscalls, which prevent hooking.

A lot more goes into AV evasion than just copying a file lol

**Comment by Im4wasp** [comment]
yeah ofc
but it works :) wasp stayed 0/76 for a few months

**Comment by iloveyumyumshrimpnoodles** [comment]
> yeah ofc but it works :) wasp stayed 0/76 for a few months

That's because Python is decent at evading AV's since they have trouble with python interpreted bytecode. Using a modified version of PyInstaller would make it even harder for AV's to detect your malicious software
And if you introduce anti techniques, like checking for virtualized environments you'll have an even greater chance of staying undetected.

I wrote an entire library for this, which uses about 37 different python techniques, 12 windows specific techniques and 15 *nix techniques, so i should know lol

**Comment by Im4wasp** [comment]
wasp is not ment to be an exe
so no need for all this

**Comment by Im4wasp** [comment]
@iloveyumyumshrimpnoodles is there a way to contact you ?

**Comment by iloveyumyumshrimpnoodles** [comment]
> @iloveyumyumshrimpnoodles is there a way to contact you ?

Not really, I only use Signal but that's limited to friends and family.
I've had all my discord accounts termed, and I'm banned from Telegram for a ToS violation (no idea why) until i get a new phone number

**Comment by Im4wasp** [comment]
> That's because Python is decent at evading AV's since they have trouble with python interpreted bytecode. Using a modified version of PyInstaller would make it even harder for AV's to detect your malicious software And if you introduce anti techniques, like checking for virtualized environments you'll have an even greater chance of staying undetected.
> I wrote an entire library for this, which uses about 37 different python techniques, 12 windows specific techniques and 15 *nix techniques, so i should know lol

I'd really love to learn more about AV evasion with Python. I'd greatly appreciate it if you could share some insights or resources with me. You seem to know your stuff!
Your unique library sounds incredibly valuable! Thanks in advance! 🐍🔓

**Comment by MJMODZZ-V3** [comment]
> 

Well sorry to mix in but like i said, i coded my own fud Rat in python, also my own crypter. Im not a python pro but if its about good M4lware you got someone righ here

**Comment by iloveyumyumshrimpnoodles** [comment]
> > 
> 
> Well sorry to mix in but like i said, i coded my own fud Rat in python, also my own crypter. Im not a python pro but if its about good M4lware you got someone righ here

Creating FUD malware in Python isn't as hard as you think, the same goes for a crypter.
Pretty cool tho

**Comment by MJMODZZ-V3** [comment]
> > > 
> > 
> > 
> > Well sorry to mix in but like i said, i coded my own fud Rat in python, also my own crypter. Im not a python pro but if its about good M4lware you got someone righ here
> 
> Creating FUD malware in Python isn't as hard as you think, the same goes for a crypter. Pretty cool tho

Well I dont code in python, thats why i asked so many Questions. I only code C#, VB and C++

**Comment by Im4wasp** [comment]
@MJMODZZ-V3 would you mind sharing your rat, so i can see the evasion technique used plz

**Comment by MJMODZZ-V3** [comment]
> @MJMODZZ-V3 would you mind sharing your rat, so i can see the evasion technique used plz

I only sall it but well i can give you the source code of another rat

**Comment by iloveyumyumshrimpnoodles** [comment]
> > @MJMODZZ-V3 would you mind sharing your rat, so i can see the evasion technique used plz
> 
> I only sall it but well i can give you the source code of another rat

Selling a Python RAT? Must be quite good then

**Comment by Im4wasp** [comment]
> I'd really love to learn more about AV evasion with Python. I'd greatly appreciate it if you could share some insights or resources with me. You seem to know your stuff! Your unique library sounds incredibly valuable! Thanks in advance! 🐍🔓
@iloveyumyumshrimpnoodles

**Comment by iloveyumyumshrimpnoodles** [comment]
> > I'd really love to learn more about AV evasion with Python. I'd greatly appreciate it if you could share some insights or resources with me. You seem to know your stuff! Your unique library sounds incredibly valuable! Thanks in advance! snakeunlock
> > @iloveyumyumshrimpnoodles

If you're expecting me to send that library, I'd have to disappoint you because I won't. Too much private stuff that I'd rather not have available for everybody, sorry.

**Comment by Im4wasp** [comment]
i wouldn't expect a FOSS advocate to say that, but no probleme i understand
Maby you have tips/techniques you wouldn't mind sharing ?

**Comment by iloveyumyumshrimpnoodles** [comment]
> i wouldn't expect a FOSS advocate to say that, but no probleme i understand Maby you have tips/techniques you wouldn't mind sharing ?

While I am a open source enjoyer, that does not mean EVERYTHING has to be published.

As for the tips, look at what other prevalent malware does and how it bypasses AV/EDR/IDS. Checkout the articles on them, as they usually post snippets of the code from which you can copy strings (registry keys, file artifacts etc)
You should also look through tools like [pafish](https://github.com/a0rtega/pafish) and [al-khaser](https://github.com/LordNoteworthy/al-khaser)

**Comment by MJMODZZ-V3** [comment]
> > > @MJMODZZ-V3 would you mind sharing your rat, so i can see the evasion technique used plz
> > 
> > 
> > I only sall it but well i can give you the source code of another rat
> 
> Selling a Python RAT? Must be quite good then

"Well I dont code in python, thats why i asked so many Questions. I only code C#, VB and C++"
~ @MJMODZZ-V3

**Comment by MJMODZZ-V3** [comment]
> i wouldn't expect a FOSS advocate to say that, but no probleme i understand Maby you have tips/techniques you wouldn't mind sharing ?

So if your interested into sharing sources of C# Rats, dm me on Telegram. Otherwise i will close this issue because i get emailed every message

**Comment by iloveyumyumshrimpnoodles** [comment]
> > i wouldn't expect a FOSS advocate to say that, but no probleme i understand Maby you have tips/techniques you wouldn't mind sharing ?
> 
> So if your interested into sharing sources of C# Rats, dm me on Telegram. Otherwise i will close this issue because i get emailed every message

Feel free to unsubscribe from the issue, as it has become more of a chatting room than an issue lol

**Comment by MJMODZZ-V3** [comment]
> > > i wouldn't expect a FOSS advocate to say that, but no probleme i understand Maby you have tips/techniques you wouldn't mind sharing ?
> > 
> > 
> > So if your interested into sharing sources of C# Rats, dm me on Telegram. Otherwise i will close this issue because i get emailed every message
> 
> Feel free to unsubscribe from the issue, as it has become more of a chatting room than an issue lol

Well this is my issue, not urs

**Comment by iloveyumyumshrimpnoodles** [comment]
> Well this is my issue, not urs

You simply opened the issue, it doesn't belong to anyone.
Are we seriously going to have an argument over to who the issue belongs?
